### ISSUE TITLE
Fix parasitic sky-hack vertical planes

### ISSUE THREAD

**Issue by Altazimuth** [team-eternity/eternity#35] opened 2016-01-26 09:09 UTC
https://www.doomworld.com/vb/eternity/85686-sky-transfer-bug/

**Comment by ioan-chera** [comment] 2016-02-06 00:08
Fixed but not fully. Parasitic sky vertical planes appear where they don't in MBF.

**Comment by ioan-chera** [comment] 2017-03-30 04:39
Fixed another discovered bug (in commit d0213a). But the main issue still remains. The difference between being in a normal sector and being above a fake ceiling is caused by this check in R_2S_Normal and equivalently in R_2S_Sloped:

```
   mark = (seg.frontsec->lightlevel != seg.backsec->lightlevel ||
           seg.line->linedef->portal ||
           seg.frontsec->heightsec != -1 ||
           seg.frontsec->heightsec != seg.backsec->heightsec ||
           seg.frontsec->midmap != seg.backsec->midmap ||
           (seg.line->sidedef->midtexture && 
            (seg.line->linedef->extflags & EX_ML_CLIPMIDTEX)));
```
heightsec becomes valid and makes the sky-hack linedef always render.

**Comment by ioan-chera** [comment] 2017-03-30 05:21
Fixed by removing the `seg.frontsec->heightsec != -1` check. Hopefully no other bugs arise from this.

**Closed by ioan-chera** 2017-03-30 05:21 UTC
Labels: bug
