### ISSUE TITLE
Feature demand: wall light settings

### ISSUE THREAD

**Issue by ioan-chera** [team-eternity/eternity#381] opened 2020-03-18 08:39 UTC
Just like how we have sector surface light settings in UDMF, also add the wall light settings if easy to do. Editors such as GZDBBF make it seem like it's available, when it's not.

**Comment by skillsawed** [comment] 2020-05-03 21:43
This is a very useful feature in ZDoom UDMF mapping - it would be awesome to have it in EE as well.

**Comment by Altazimuth** [comment] 2020-05-03 22:19
I had actually written code to do this that sadly got lost. The reason I never committed it was due to concerns of making the renderer slower due to side_t being larger. Given printz's comments on alignment the other day it turns out there's two bytes to spare in side_t before making it larger due to alignment. The problem is that to do this properly you'd need add more than that, requiring at least 8 bits for flags and an unknown amount for the actual lighting value (16 bits would be sensible enough most likely).

**Closed** 2023-06-27 22:54 UTC
Labels: enhancement, rendering
