### ISSUE TITLE
Not loading PWADs GFX in GUI

### ISSUE THREAD

**Issue by No-Kelvin** [team-eternity/eternity#10] opened 2015-01-20 10:15 UTC
Eternity does not seem to be loading some of GFX when loading a PWAD from the in-game menu. e.g. Hell Revealed 2's green arrow (on menu). the traditional doom2's skull is shown instead.

the green arrow appear when using -file parameter.

**Comment by Altazimuth** [comment] 2016-08-19 22:33
I believe this is somewhat due to how flawed the in-game loading is. Loading anything that tinkers with stuff like palettes, icons, graphics etc never ends well. At the moment I would strongly suggest NOT using the in-game loader for anything that has lots of new assets. It's definitely something worth looking into fixing though.

**Comment by ioan-chera** [comment] 2017-01-29 19:09
In my case, I see the green menu arrow loading alright, but the status bar doesn't get updated.

**Comment by ioan-chera** [comment] 2017-01-30 06:44
Status bar has been fixed (for DOOM). I still can't reproduce the menu cursor issue, even though it's worth checking the code for it. But I'm noticing the problem elsewhere:
* the message font doesn't get updated;
* it's possible the Heretic status bar currently doesn't get fully updated;
* could be others.
So I'm not closing the issue yet.

**Comment by ioan-chera** [comment] 2017-01-31 19:15
Fixed and closed. May open new issues later if necessary if it still exists.

**Closed by ioan-chera** 2017-01-31 19:15 UTC
Labels: bug
